In [1]:
import torch

In [2]:
print(torch.__version__)
print(torch.cuda.is_available())

2.12.1+cpu
False


In [3]:
scalar=torch.tensor(1)
scalar

tensor(1)

In [4]:
scalar.ndim

0

In [5]:
scalar.shape

torch.Size([])

In [6]:
vector=torch.tensor([1,2])
vector

tensor([1, 2])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
matrix=torch.tensor([[1,2],[3,4],[5,6]])
matrix

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [10]:
matrix.ndim

2

In [11]:
matrix.shape

torch.Size([3, 2])

In [12]:
tensor=torch.tensor([[[[1,2,3],[4,5,6],[7,8,9]]]])
tensor

tensor([[[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]])

In [13]:
tensor.ndim

4

In [14]:
tensor.shape

torch.Size([1, 1, 3, 3])

In [15]:
random_tensor=torch.rand(4,8)
random_tensor

tensor([[0.8784, 0.0672, 0.2193, 0.8576, 0.0868, 0.0691, 0.2061, 0.8098],
        [0.7549, 0.1087, 0.5451, 0.2272, 0.9649, 0.2817, 0.3677, 0.3454],
        [0.6221, 0.4639, 0.4037, 0.0436, 0.7627, 0.1272, 0.2890, 0.1893],
        [0.8192, 0.3775, 0.0616, 0.1570, 0.6538, 0.0067, 0.5831, 0.5675]])

In [16]:
random_tensor_image=torch.rand(3,224,224)
random_tensor_image.shape,random_tensor_image.ndim

(torch.Size([3, 224, 224]), 3)

In [17]:
zero_tensor=torch.zeros(3,3)
zero_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [18]:
one_tensor=torch.ones(3,3)
one_tensor

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [19]:
zero_tensor*one_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [20]:
one_to_ten=torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
ten_zeros=torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [22]:
float32_tensor=torch.tensor((3,6,9),dtype=torch.float32,device=None,requires_grad=False)
float32_tensor.dtype

torch.float32

In [23]:
float16_tensor=float32_tensor.type(torch.float16)
float16_tensor.dtype

torch.float16

In [24]:
float16_tensor*float32_tensor

tensor([ 9., 36., 81.])

In [25]:
tensor=torch.tensor((1,2,3))
torch.matmul(tensor,tensor)

tensor(14)

In [75]:
# mat_a=torch.tensor([[1,2],[3,4],[5,6]])
# mat_b=torch.tensor([[7,8],[9,10],[11,12]])
# torch.matmul(mat_a,mat_b)
# ---------------------------------------------------------------------------
# RuntimeError                              Traceback (most recent call last)
# Cell In[26], line 3
#       1 mat_a=torch.tensor([[1,2],[3,4],[5,6]])
#       2 mat_b=torch.tensor([[7,8],[9,10],[11,12]])
# ----> 3 torch.matmul(mat_a,mat_b)

# RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [27]:
mat_a

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [28]:
mat_b

tensor([[ 7,  8],
        [ 9, 10],
        [11, 12]])

In [29]:
mat_b.T

tensor([[ 7,  9, 11],
        [ 8, 10, 12]])

In [30]:
c=torch.matmul(mat_a,mat_b.T)
c

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

In [31]:
torch.min(c)

tensor(23)

In [32]:
torch.max(c)

tensor(127)

In [73]:
# torch.mean(c)
# ---------------------------------------------------------------------------
# RuntimeError                              Traceback (most recent call last)
# Cell In[33], line 1
# ----> 1 torch.mean(c)

# RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [34]:
torch.mean(c.type(torch.float32))

tensor(67.)

In [35]:
torch.median(c.type(torch.float32))

tensor(67.)

In [36]:
torch.sum(c)

tensor(603)

In [37]:
torch.argmin(c)

tensor(0)

In [38]:
torch.argmax(c)

tensor(8)

In [39]:
c[2,2]

tensor(127)

In [72]:
# #c[8]
# ---------------------------------------------------------------------------
# IndexError                                Traceback (most recent call last)
# Cell In[40], line 1
# ----> 1 c[8]

# IndexError: index 8 is out of bounds for dimension 0 with size 3

In [41]:
torch.argmax(c,dim=0)

tensor([2, 2, 2])

In [42]:
torch.argmax(c,dim=1)

tensor([2, 2, 2])

In [43]:
idx=torch.argmax(c)
row,col=torch.unravel_index(idx,c.shape)
print(row.item(),col.item())

2 2


In [44]:
c

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

In [45]:
reshaped_c=c.reshape(1,9)
reshaped_c

tensor([[ 23,  29,  35,  53,  67,  81,  83, 105, 127]])

In [46]:
reshaped_c[0,0]=10
reshaped_c

tensor([[ 10,  29,  35,  53,  67,  81,  83, 105, 127]])

In [47]:
c

tensor([[ 10,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

In [48]:
view_c=c.view(1,9)
view_c

tensor([[ 10,  29,  35,  53,  67,  81,  83, 105, 127]])

In [49]:
view_c

tensor([[ 10,  29,  35,  53,  67,  81,  83, 105, 127]])

In [50]:
view_c[0,0]=5
view_c

tensor([[  5,  29,  35,  53,  67,  81,  83, 105, 127]])

In [51]:
c

tensor([[  5,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

In [52]:
reshaped_c

tensor([[  5,  29,  35,  53,  67,  81,  83, 105, 127]])

In [53]:
print(c.data_ptr())
print(reshaped_c.data_ptr())
print(view_c.data_ptr())

3955128074880
3955128074880
3955128074880


In [54]:
c_stack_0=torch.stack([c,c,c,c],dim=0)
c_stack_0

tensor([[[  5,  29,  35],
         [ 53,  67,  81],
         [ 83, 105, 127]],

        [[  5,  29,  35],
         [ 53,  67,  81],
         [ 83, 105, 127]],

        [[  5,  29,  35],
         [ 53,  67,  81],
         [ 83, 105, 127]],

        [[  5,  29,  35],
         [ 53,  67,  81],
         [ 83, 105, 127]]])

In [55]:
c_stack_1=torch.stack([c,c,c,c],dim=1)
c_stack_1

tensor([[[  5,  29,  35],
         [  5,  29,  35],
         [  5,  29,  35],
         [  5,  29,  35]],

        [[ 53,  67,  81],
         [ 53,  67,  81],
         [ 53,  67,  81],
         [ 53,  67,  81]],

        [[ 83, 105, 127],
         [ 83, 105, 127],
         [ 83, 105, 127],
         [ 83, 105, 127]]])

In [56]:
c

tensor([[  5,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

In [57]:
c_vstack=torch.vstack([c,c,c,c])
c_vstack

tensor([[  5,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127],
        [  5,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127],
        [  5,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127],
        [  5,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

In [58]:
c_hstack=torch.hstack([c,c,c,c])
c_hstack

tensor([[  5,  29,  35,   5,  29,  35,   5,  29,  35,   5,  29,  35],
        [ 53,  67,  81,  53,  67,  81,  53,  67,  81,  53,  67,  81],
        [ 83, 105, 127,  83, 105, 127,  83, 105, 127,  83, 105, 127]])

In [59]:
print(view_c.shape)
view_c

torch.Size([1, 9])


tensor([[  5,  29,  35,  53,  67,  81,  83, 105, 127]])

In [60]:
squeezed_c=torch.squeeze(view_c)
print(squeezed_c.shape)
squeezed_c

torch.Size([9])


tensor([  5,  29,  35,  53,  67,  81,  83, 105, 127])

In [61]:
unsqueezed_c=torch.unsqueeze(squeezed_c,dim=1)
print(unsqueezed_c.shape)
unsqueezed_c

torch.Size([9, 1])


tensor([[  5],
        [ 29],
        [ 35],
        [ 53],
        [ 67],
        [ 81],
        [ 83],
        [105],
        [127]])

In [62]:
image_x=torch.rand(224,224,3)
image_x.shape

torch.Size([224, 224, 3])

In [65]:
permute_x=torch.permute(image_x,(2,0,1))
permute_x.shape

torch.Size([3, 224, 224])

In [66]:
c

tensor([[  5,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

In [68]:
c_permute=torch.permute(c,(1,0))
c_permute

tensor([[  5,  53,  83],
        [ 29,  67, 105],
        [ 35,  81, 127]])

In [69]:
c[0,0]=10
c

tensor([[ 10,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

In [70]:
c_permute

tensor([[ 10,  53,  83],
        [ 29,  67, 105],
        [ 35,  81, 127]])

In [71]:
c

tensor([[ 10,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

In [76]:
c.shape

torch.Size([3, 3])

In [78]:
c_reshaped=torch.reshape(c,(1,3,3))
c_reshaped.shape

torch.Size([1, 3, 3])

In [80]:
c_reshaped

tensor([[[ 10,  29,  35],
         [ 53,  67,  81],
         [ 83, 105, 127]]])

In [81]:
c_reshaped[0,2,2]

tensor(127)

In [83]:
c_reshaped[0,:,2]

tensor([ 35,  81, 127])

In [84]:
import numpy as np

In [85]:
c

tensor([[ 10,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

In [88]:
numpy_c=c.numpy()
numpy_c

array([[ 10,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]])

In [89]:
numpy_c.dtype

dtype('int64')

In [96]:
array=np.arange(1,11)
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [97]:
numpy_tensor=torch.from_numpy(array)
numpy_tensor

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [98]:
numpy_tensor.dtype

torch.int64

In [104]:
array=array+1
array,numpy_tensor

(array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16]),
 tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]))

In [105]:
array+=1
array,numpy_tensor

(array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17]),
 tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]))

In [106]:
numpy_tensor

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [112]:
torch.manual_seed(18)
random_tensor_a=torch.rand(3,4)
torch.manual_seed(18)
random_tensor_b=torch.rand(3,4)
print(random_tensor_a)
print(random_tensor_b)
print(random_tensor_a==random_tensor_b)

tensor([[0.4958, 0.4588, 0.3961, 0.7521],
        [0.9220, 0.6045, 0.5511, 0.5441],
        [0.1717, 0.2169, 0.0349, 0.9457]])
tensor([[0.4958, 0.4588, 0.3961, 0.7521],
        [0.9220, 0.6045, 0.5511, 0.5441],
        [0.1717, 0.2169, 0.0349, 0.9457]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
