In [2]:
import torch

In [6]:
print(torch.__version__)
print(torch.cuda.is_available())

2.12.1+cpu
False


In [8]:
scalar=torch.tensor(1)
scalar

tensor(1)

In [9]:
scalar.ndim

0

In [10]:
scalar.shape

torch.Size([])

In [12]:
vector=torch.tensor([1,2])
vector

tensor([1, 2])

In [13]:
vector.ndim

1

In [14]:
vector.shape

torch.Size([2])

In [16]:
matrix=torch.tensor([[1,2],[3,4],[5,6]])
matrix

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [17]:
matrix.ndim

2

In [18]:
matrix.shape

torch.Size([3, 2])

In [19]:
tensor=torch.tensor([[[[1,2,3],[4,5,6],[7,8,9]]]])
tensor

tensor([[[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]])

In [20]:
tensor.ndim

4

In [21]:
tensor.shape

torch.Size([1, 1, 3, 3])

In [22]:
random_tensor=torch.rand(4,8)
random_tensor

tensor([[2.9766e-02, 3.1299e-01, 5.3036e-01, 2.9763e-01, 1.3587e-01, 9.3512e-01,
         9.8556e-01, 3.5661e-04],
        [5.1095e-01, 8.5395e-01, 5.0982e-01, 5.6947e-01, 2.2202e-02, 9.3812e-01,
         2.7003e-01, 1.5242e-01],
        [2.9904e-01, 8.2399e-01, 8.7147e-01, 7.8354e-01, 9.3878e-01, 6.8819e-01,
         9.5526e-02, 8.1649e-01],
        [1.6901e-01, 6.4026e-02, 2.2917e-01, 4.7838e-02, 7.5861e-01, 8.2195e-01,
         8.3363e-01, 7.9515e-01]])

In [23]:
random_tensor_image=torch.rand(3,224,224)
random_tensor_image.shape,random_tensor_image.ndim

(torch.Size([3, 224, 224]), 3)

In [25]:
zero_tensor=torch.zeros(3,3)
zero_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [26]:
one_tensor=torch.ones(3,3)
one_tensor

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [27]:
zero_tensor*one_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [34]:
one_to_ten=torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
ten_zeros=torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [45]:
float32_tensor=torch.tensor((3,6,9),dtype=torch.float32,device=None,requires_grad=False)
float32_tensor.dtype

torch.float32

In [48]:
float16_tensor=float32_tensor.type(torch.float16)
float16_tensor.dtype

torch.float16

In [49]:
float16_tensor*float32_tensor

tensor([ 9., 36., 81.])

In [5]:
tensor=torch.tensor((1,2,3))
torch.matmul(tensor,tensor)

tensor(14)