In [1]:
import numpy as np
a=np.zeros(25)
a[4:10]=1
print(a)

[0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0.]


In [4]:
a=np.arange(5,21)
a=a[::-1]
print(a)

[20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5]


In [10]:
a=np.random.randint(1,100,10)
print(a)
a[:5]=np.sort(a[:5])
a[5:]=np.sort(a[5:])[::-1]
print(a)

[ 8  2 66 85 82 41 17 67  4 22]
[ 2  8 66 82 85 67 41 22 17  4]


In [11]:
a=np.linspace(0,1,12)[1:-1]
print(a)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [12]:
a=np.array(['a','b','c'])
b=np.array(['d','e','f'])
c=a+b
print(c)

['ad' 'be' 'cf']


In [14]:
a=np.random.rand(4,3)
print(np.max(a))
print(np.min(a))

0.8608238656247392
0.029259257537066485


In [18]:
a=np.ones((5,5))
a[1:-1,1:-1]=0
print(a)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [22]:
a=np.zeros((5,5))
x=[1,2,3,4]
for i in range(0,4):
    a[i,i+1]=x[i]
    a[i+1,i]=x[i]
print(a)

[[0. 1. 0. 0. 0.]
 [1. 0. 2. 0. 0.]
 [0. 2. 0. 3. 0.]
 [0. 0. 3. 0. 4.]
 [0. 0. 0. 4. 0.]]


In [27]:
a=np.random.rand(10,10)
blocks=[]
for i in range(0,8):
    for j in range(0,8):
        block=a[i:i+3,j:j+3]
        blocks.append(block)
print(len(blocks))

64


In [32]:
a = np.array([[17,24,1,8,15],[23,5,7,14,16],[4,6,13,20,22],[10,12,19,21,3],[11,18,25,2,9]])
rows=np.sum(a,axis=0)
column=np.sum(a,axis=1)
print(max(rows.max(),column.max(),rows.min(),column.min(),np.sum(np.diag(a)),np.sum(np.diag(np.fliplr(a)))))
print(min(rows.max(),column.max(),rows.min(),column.min(),np.sum(np.diag(a)),np.sum(np.diag(np.fliplr(a)))))

65
65
